// generated by nuxt-seo-kit
import type { ModuleOptions } from 'nuxt-seo-kit'
declare module '#nuxt-seo-kit/config' {
  export const splash: true | ModuleOptions['splash']
  export const siteName: "Paget.dk" | ModuleOptions['siteName']
  export const siteDescription: "Velkommen til Paget.dk!" | ModuleOptions['siteDescription']
  export const siteImage: undefined | ModuleOptions['siteImage']
  export const siteUrl: "https://paget.dk" | ModuleOptions['siteUrl']
  export const titleSeparator: "|" | ModuleOptions['titleSeparator']
  export const trailingSlash: false | ModuleOptions['trailingSlash']
  export const language: "da-DK" | ModuleOptions['language']
  export const indexable: true | ModuleOptions['indexable']
}
