// generated by nuxt-seo-kit
import type { ModuleOptions } from 'nuxt-seo-kit'
declare module '#nuxt-seo-kit/config' {
  export const splash: ModuleOptions['splash']
  export const siteName: ModuleOptions['siteName']
  export const siteDescription: ModuleOptions['siteDescription']
  export const siteImage: ModuleOptions['siteImage']
  export const siteUrl: ModuleOptions['siteUrl']
  export const titleSeparator: ModuleOptions['titleSeparator']
  export const trailingSlash: ModuleOptions['trailingSlash']
  export const language: ModuleOptions['language']
  export const indexable: ModuleOptions['indexable']
}
