// generated by nuxt-simple-sitemap
import type { ModuleOptions } from 'nuxt-simple-sitemap'
declare module '#nuxt-simple-sitemap/config' {
  export const include: ["/**"] | ModuleOptions['include']
  export const hostname: "https://selfhosting.ninja" | ModuleOptions['hostname']
  export const trailingSlash: false | ModuleOptions['trailingSlash']
  export const enabled: true | ModuleOptions['enabled']
  export const urls: [{"url":"/"},{"url":"/gal"},{"url":"/form"},{"url":"/test"},{"url":"/text"},{"url":"/login"},{"url":"/pimox"},{"url":"/esplora"},{"url":"/gallery"},{"url":"/weather"},{"url":"/flagQuiz"},{"url":"/aboutPage"},{"url":"/calculator"},{"url":"/flagQuizV2"},{"url":"/flagQuizV3"},{"url":"/flagQuizV4"},{"url":"/flagQuizV5"},{"url":"/vueusetest"},{"url":"/countryQuiz"},{"url":"/countrygame"},{"url":"/storagetest"},{"url":"/successPage"},{"url":"/testvuetify"},{"url":"/supabasetest"},{"url":"/countryQuizV2"},{"url":"/countryQuizV3"},{"url":"/countryQuizV4"},{"url":"/restcountries"},{"url":"/swipergallery"},{"url":"/cloudinaryTest"},{"url":"/galleryprismic"},{"url":"/flagQuizV6ApiParty"},{"url":"/flagQuizV7ApiParty"}] | ModuleOptions['urls']
  export const defaults: {} | ModuleOptions['defaults']
  export const devPreview: true | ModuleOptions['devPreview']
  export const inferStaticPagesAsRoutes: true | ModuleOptions['inferStaticPagesAsRoutes']
}
