// generated by nuxt-seo-kit
import type { ModuleOptions } from 'nuxt-seo-kit'
declare module '#nuxt-seo-kit/config' {
  export const splash: true | ModuleOptions['splash']
  export const siteName: "Selfhosting.ninja" | ModuleOptions['siteName']
  export const siteDescription: "Selfhosting.ninja is a blog about selfhosting your own homelab, Home Assistant, Docker, Kubernetes and much more." | ModuleOptions['siteDescription']
  export const siteImage: undefined | ModuleOptions['siteImage']
  export const siteUrl: "https://selfhosting.ninja" | ModuleOptions['siteUrl']
  export const titleSeparator: "|" | ModuleOptions['titleSeparator']
  export const trailingSlash: false | ModuleOptions['trailingSlash']
  export const language: "en-US" | ModuleOptions['language']
  export const indexable: true | ModuleOptions['indexable']
}
