
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'Card': typeof import("../components/content/Card.vue")['default']
    'Hero': typeof import("../components/content/Hero.vue")['default']
    'ImageContent': typeof import("../components/content/ImageContent.vue")['default']
    'ProseCode': typeof import("../components/content/ProseCode.vue")['default']
    'AppFooter': typeof import("../components/AppFooter.vue")['default']
    'AppMenu': typeof import("../components/AppMenu.vue")['default']
    'AppMenuBar': typeof import("../components/AppMenuBar.vue")['default']
    'AppMenuUpdated': typeof import("../components/AppMenuUpdated.vue")['default']
    'AppMenuV1': typeof import("../components/AppMenuV1.vue")['default']
    'AppMenuV2': typeof import("../components/AppMenuV2.vue")['default']
    'AppMenuV4': typeof import("../components/AppMenuV4.vue")['default']
    'AppMenuV5': typeof import("../components/AppMenuV5.vue")['default']
    'Auth': typeof import("../components/Auth.vue")['default']
    'ColorModeSwitch': typeof import("../components/ColorModeSwitch.vue")['default']
    'ColorModeSwitchV2': typeof import("../components/ColorModeSwitchV2.vue")['default']
    'DocumentDrivenEmpty': typeof import("../components/DocumentDrivenEmpty.vue")['default']
    'DocumentDrivenNotFound': typeof import("../components/DocumentDrivenNotFound.vue")['default']
    'EndQuizComponent': typeof import("../components/EndQuizComponent.vue")['default']
    'GeoComponent': typeof import("../components/GeoComponent.vue")['default']
    'MainQuizComponent': typeof import("../components/MainQuizComponent.vue")['default']
    'MainQuizComponentFetch': typeof import("../components/MainQuizComponentFetch.vue")['default']
    'MainQuizComponentFetchOld': typeof import("../components/MainQuizComponentFetchOld.vue")['default']
    'PrimeMegaMenu': typeof import("../components/PrimeMegaMenu.vue")['default']
    'PrimevueMenubar': typeof import("../components/PrimevueMenubar.vue")['default']
    'PrismicGallery': typeof import("../components/PrismicGallery.vue")['default']
    'ScrollToTop': typeof import("../components/ScrollToTop.vue")['default']
    'SplideGallery': typeof import("../components/SplideGallery.vue")['default']
    'StartQuizComponent': typeof import("../components/StartQuizComponent.vue")['default']
    'TableOfContents': typeof import("../components/TableOfContents.vue")['default']
    'ThemeControllerDaisy': typeof import("../components/ThemeControllerDaisy.vue")['default']
    'TopBC': typeof import("../components/TopBC.vue")['default']
    'CloudinaryGalleryComponent': typeof import("../components/cloudinaryGalleryComponent.vue")['default']
    'FlagQuizComponent': typeof import("../components/flagQuizComponent.vue")['default']
    'FlagQuizQuestions': typeof import("../components/flagQuizQuestions.vue")['default']
    'FlagQuizResults': typeof import("../components/flagQuizResults.vue")['default']
    'FlagQuizStart': typeof import("../components/flagQuizStart.vue")['default']
    'ImageGridComponent': typeof import("../components/imageGridComponent.vue")['default']
    'QuizLogic': typeof import("../components/quizLogic.vue")['default']
    'RandomCountry': typeof import("../components/randomCountry.vue")['default']
    'ContentDoc': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue")['default']
    'ContentList': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentList.vue")['default']
    'ContentNavigation': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue")['default']
    'ContentQuery': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue")['default']
    'ContentRenderer': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
    'ContentRendererMarkdown': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue")['default']
    'ContentSlot': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue")['default']
    'Markdown': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Markdown.vue")['default']
    'ProseCodeInline': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default']
    'ProsePre': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue")['default']
    'ProseA': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']
    'ProseBlockquote': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
    'ProseEm': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
    'ProseH1': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
    'ProseH2': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
    'ProseH3': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
    'ProseH4': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
    'ProseH5': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
    'ProseH6': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
    'ProseHr': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
    'ProseImg': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
    'ProseLi': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
    'ProseOl': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
    'ProseP': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
    'ProseScript': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
    'ProseStrong': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
    'ProseTable': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
    'ProseTbody': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
    'ProseTd': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
    'ProseTh': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
    'ProseThead': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
    'ProseTr': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
    'ProseUl': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
    'CookieControl': typeof import("../node_modules/@dargmuesli/nuxt-cookie-control/dist/runtime/components/CookieControl.vue")['default']
    'CookieIframe': typeof import("../node_modules/@dargmuesli/nuxt-cookie-control/dist/runtime/components/CookieIframe.vue")['default']
    'TransitionExpand': typeof import("../node_modules/@morev/vue-transitions/nuxt/vue-transitions/transition-expand.vue")['default']
    'TransitionFade': typeof import("../node_modules/@morev/vue-transitions/nuxt/vue-transitions/transition-fade.vue")['default']
    'TransitionScale': typeof import("../node_modules/@morev/vue-transitions/nuxt/vue-transitions/transition-scale.vue")['default']
    'TransitionSlide': typeof import("../node_modules/@morev/vue-transitions/nuxt/vue-transitions/transition-slide.vue")['default']
    'CldImage': typeof import("../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldImage.vue")['default']
    'CldMediaLibrary': typeof import("../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldMediaLibrary.vue")['default']
    'CldOgImage': typeof import("../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldOgImage.vue")['default']
    'CldProductGallery': typeof import("../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldProductGallery.vue")['default']
    'CldUploadButton': typeof import("../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldUploadButton.vue")['default']
    'CldUploadWidget': typeof import("../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldUploadWidget.vue")['default']
    'CldVideoPlayer': typeof import("../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldVideoPlayer.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'MDC': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
    'MDCRenderer': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
    'MDCSlot': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
    'ColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'Icon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'IconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'Swiper': typeof import("../node_modules/swiper/swiper-vue")['Swiper']
    'SwiperSlide': typeof import("../node_modules/swiper/swiper-vue")['SwiperSlide']
    'HeadlessCombobox': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/combobox/combobox")['Combobox']
    'HeadlessComboboxLabel': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxLabel']
    'HeadlessComboboxButton': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxButton']
    'HeadlessComboboxInput': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxInput']
    'HeadlessComboboxOptions': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxOptions']
    'HeadlessComboboxOption': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxOption']
    'HeadlessDialog': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/dialog/dialog")['Dialog']
    'HeadlessDialogOverlay': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogOverlay']
    'HeadlessDialogBackdrop': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogBackdrop']
    'HeadlessDialogPanel': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogPanel']
    'HeadlessDialogTitle': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogTitle']
    'HeadlessDialogDescription': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogDescription']
    'HeadlessDisclosure': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['Disclosure']
    'HeadlessDisclosureButton': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['DisclosureButton']
    'HeadlessDisclosurePanel': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['DisclosurePanel']
    'HeadlessFocusTrap': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/focus-trap/focus-trap")['FocusTrap']
    'HeadlessListbox': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/listbox/listbox")['Listbox']
    'HeadlessListboxLabel': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxLabel']
    'HeadlessListboxButton': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxButton']
    'HeadlessListboxOptions': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxOptions']
    'HeadlessListboxOption': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxOption']
    'HeadlessMenu': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/menu/menu")['Menu']
    'HeadlessMenuButton': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/menu/menu")['MenuButton']
    'HeadlessMenuItems': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/menu/menu")['MenuItems']
    'HeadlessMenuItem': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/menu/menu")['MenuItem']
    'HeadlessPopover': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/popover/popover")['Popover']
    'HeadlessPopoverButton': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverButton']
    'HeadlessPopoverOverlay': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverOverlay']
    'HeadlessPopoverPanel': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverPanel']
    'HeadlessPopoverGroup': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverGroup']
    'HeadlessPortal': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/portal/portal")['Portal']
    'HeadlessPortalGroup': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/portal/portal")['PortalGroup']
    'HeadlessRadioGroup': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroup']
    'HeadlessRadioGroupOption': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupOption']
    'HeadlessRadioGroupLabel': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupLabel']
    'HeadlessRadioGroupDescription': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupDescription']
    'HeadlessSwitchGroup': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchGroup']
    'HeadlessSwitch': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/switch/switch")['Switch']
    'HeadlessSwitchLabel': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchLabel']
    'HeadlessSwitchDescription': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchDescription']
    'HeadlessTabGroup': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabGroup']
    'HeadlessTabList': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabList']
    'HeadlessTab': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/tabs/tabs")['Tab']
    'HeadlessTabPanels': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabPanels']
    'HeadlessTabPanel': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabPanel']
    'HeadlessTransitionChild': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/transitions/transition")['TransitionChild']
    'HeadlessTransitionRoot': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/transitions/transition")['TransitionRoot']
    'TresCanvas': typeof import("../node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.client.vue")['default']
    'TresCanvas': IslandComponent<typeof import("../node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.server.vue")['default']>
    'Carousel': typeof import("../node_modules/vue3-carousel/dist/carousel.es")['Carousel']
    'Slide': typeof import("../node_modules/vue3-carousel/dist/carousel.es")['Slide']
    'Pagination': typeof import("../node_modules/vue3-carousel/dist/carousel.es")['Pagination']
    'Navigation': typeof import("../node_modules/vue3-carousel/dist/carousel.es")['Navigation']
    'SiteLink': typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
    'RobotMeta': typeof import("../node_modules/@nuxtjs/robots/dist/runtime/nuxt/components/RobotMeta")['default']
    'OgImage': typeof import("../node_modules/@nuxtjs/seo/node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImage")['default']
    'OgImageScreenshot': typeof import("../node_modules/@nuxtjs/seo/node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImageScreenshot")['default']
    'SchemaOrgDebug': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgDebug']
    'SchemaOrgArticle': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgArticle']
    'SchemaOrgBreadcrumb': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgBreadcrumb']
    'SchemaOrgComment': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgComment']
    'SchemaOrgEvent': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgEvent']
    'SchemaOrgFoodEstablishment': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgFoodEstablishment']
    'SchemaOrgHowTo': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgHowTo']
    'SchemaOrgImage': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgImage']
    'SchemaOrgJobPosting': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgJobPosting']
    'SchemaOrgLocalBusiness': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgLocalBusiness']
    'SchemaOrgOrganization': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgOrganization']
    'SchemaOrgPerson': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgPerson']
    'SchemaOrgProduct': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgProduct']
    'SchemaOrgQuestion': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgQuestion']
    'SchemaOrgRecipe': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgRecipe']
    'SchemaOrgReview': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgReview']
    'SchemaOrgVideo': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgVideo']
    'SchemaOrgWebPage': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgWebPage']
    'SchemaOrgWebSite': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgWebSite']
    'SchemaOrgMovie': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgMovie']
    'SchemaOrgCourse': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgCourse']
    'SchemaOrgItemList': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgItemList']
    'SchemaOrgBook': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgBook']
    'SchemaOrgSoftwareApp': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgSoftwareApp']
    'NuxtParticles': typeof import("../node_modules/nuxt-particles/dist/runtime/components/NuxtParticles.vue")['default']
    'Motion': typeof import("../node_modules/@oku-ui/motion/dist/index")['Motion']
    'Presence': typeof import("../node_modules/@oku-ui/motion/dist/index")['Presence']
    'PresenceGroup': typeof import("../node_modules/@oku-ui/motion/dist/index")['PresenceGroup']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyCard': typeof import("../components/content/Card.vue")['default']
    'LazyHero': typeof import("../components/content/Hero.vue")['default']
    'LazyImageContent': typeof import("../components/content/ImageContent.vue")['default']
    'LazyProseCode': typeof import("../components/content/ProseCode.vue")['default']
    'LazyAppFooter': typeof import("../components/AppFooter.vue")['default']
    'LazyAppMenu': typeof import("../components/AppMenu.vue")['default']
    'LazyAppMenuBar': typeof import("../components/AppMenuBar.vue")['default']
    'LazyAppMenuUpdated': typeof import("../components/AppMenuUpdated.vue")['default']
    'LazyAppMenuV1': typeof import("../components/AppMenuV1.vue")['default']
    'LazyAppMenuV2': typeof import("../components/AppMenuV2.vue")['default']
    'LazyAppMenuV4': typeof import("../components/AppMenuV4.vue")['default']
    'LazyAppMenuV5': typeof import("../components/AppMenuV5.vue")['default']
    'LazyAuth': typeof import("../components/Auth.vue")['default']
    'LazyColorModeSwitch': typeof import("../components/ColorModeSwitch.vue")['default']
    'LazyColorModeSwitchV2': typeof import("../components/ColorModeSwitchV2.vue")['default']
    'LazyDocumentDrivenEmpty': typeof import("../components/DocumentDrivenEmpty.vue")['default']
    'LazyDocumentDrivenNotFound': typeof import("../components/DocumentDrivenNotFound.vue")['default']
    'LazyEndQuizComponent': typeof import("../components/EndQuizComponent.vue")['default']
    'LazyGeoComponent': typeof import("../components/GeoComponent.vue")['default']
    'LazyMainQuizComponent': typeof import("../components/MainQuizComponent.vue")['default']
    'LazyMainQuizComponentFetch': typeof import("../components/MainQuizComponentFetch.vue")['default']
    'LazyMainQuizComponentFetchOld': typeof import("../components/MainQuizComponentFetchOld.vue")['default']
    'LazyPrimeMegaMenu': typeof import("../components/PrimeMegaMenu.vue")['default']
    'LazyPrimevueMenubar': typeof import("../components/PrimevueMenubar.vue")['default']
    'LazyPrismicGallery': typeof import("../components/PrismicGallery.vue")['default']
    'LazyScrollToTop': typeof import("../components/ScrollToTop.vue")['default']
    'LazySplideGallery': typeof import("../components/SplideGallery.vue")['default']
    'LazyStartQuizComponent': typeof import("../components/StartQuizComponent.vue")['default']
    'LazyTableOfContents': typeof import("../components/TableOfContents.vue")['default']
    'LazyThemeControllerDaisy': typeof import("../components/ThemeControllerDaisy.vue")['default']
    'LazyTopBC': typeof import("../components/TopBC.vue")['default']
    'LazyCloudinaryGalleryComponent': typeof import("../components/cloudinaryGalleryComponent.vue")['default']
    'LazyFlagQuizComponent': typeof import("../components/flagQuizComponent.vue")['default']
    'LazyFlagQuizQuestions': typeof import("../components/flagQuizQuestions.vue")['default']
    'LazyFlagQuizResults': typeof import("../components/flagQuizResults.vue")['default']
    'LazyFlagQuizStart': typeof import("../components/flagQuizStart.vue")['default']
    'LazyImageGridComponent': typeof import("../components/imageGridComponent.vue")['default']
    'LazyQuizLogic': typeof import("../components/quizLogic.vue")['default']
    'LazyRandomCountry': typeof import("../components/randomCountry.vue")['default']
    'LazyContentDoc': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue")['default']
    'LazyContentList': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentList.vue")['default']
    'LazyContentNavigation': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue")['default']
    'LazyContentQuery': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue")['default']
    'LazyContentRenderer': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
    'LazyContentRendererMarkdown': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue")['default']
    'LazyContentSlot': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue")['default']
    'LazyMarkdown': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Markdown.vue")['default']
    'LazyProseCodeInline': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default']
    'LazyProsePre': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue")['default']
    'LazyProseA': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']
    'LazyProseBlockquote': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
    'LazyProseEm': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
    'LazyProseH1': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
    'LazyProseH2': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
    'LazyProseH3': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
    'LazyProseH4': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
    'LazyProseH5': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
    'LazyProseH6': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
    'LazyProseHr': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
    'LazyProseImg': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
    'LazyProseLi': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
    'LazyProseOl': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
    'LazyProseP': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
    'LazyProseScript': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
    'LazyProseStrong': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
    'LazyProseTable': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
    'LazyProseTbody': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
    'LazyProseTd': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
    'LazyProseTh': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
    'LazyProseThead': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
    'LazyProseTr': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
    'LazyProseUl': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
    'LazyCookieControl': typeof import("../node_modules/@dargmuesli/nuxt-cookie-control/dist/runtime/components/CookieControl.vue")['default']
    'LazyCookieIframe': typeof import("../node_modules/@dargmuesli/nuxt-cookie-control/dist/runtime/components/CookieIframe.vue")['default']
    'LazyTransitionExpand': typeof import("../node_modules/@morev/vue-transitions/nuxt/vue-transitions/transition-expand.vue")['default']
    'LazyTransitionFade': typeof import("../node_modules/@morev/vue-transitions/nuxt/vue-transitions/transition-fade.vue")['default']
    'LazyTransitionScale': typeof import("../node_modules/@morev/vue-transitions/nuxt/vue-transitions/transition-scale.vue")['default']
    'LazyTransitionSlide': typeof import("../node_modules/@morev/vue-transitions/nuxt/vue-transitions/transition-slide.vue")['default']
    'LazyCldImage': typeof import("../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldImage.vue")['default']
    'LazyCldMediaLibrary': typeof import("../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldMediaLibrary.vue")['default']
    'LazyCldOgImage': typeof import("../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldOgImage.vue")['default']
    'LazyCldProductGallery': typeof import("../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldProductGallery.vue")['default']
    'LazyCldUploadButton': typeof import("../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldUploadButton.vue")['default']
    'LazyCldUploadWidget': typeof import("../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldUploadWidget.vue")['default']
    'LazyCldVideoPlayer': typeof import("../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldVideoPlayer.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'LazyMDC': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
    'LazyMDCRenderer': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
    'LazyMDCSlot': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
    'LazyColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'LazyIcon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'LazyIconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'LazySwiper': typeof import("../node_modules/swiper/swiper-vue")['Swiper']
    'LazySwiperSlide': typeof import("../node_modules/swiper/swiper-vue")['SwiperSlide']
    'LazyHeadlessCombobox': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/combobox/combobox")['Combobox']
    'LazyHeadlessComboboxLabel': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxLabel']
    'LazyHeadlessComboboxButton': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxButton']
    'LazyHeadlessComboboxInput': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxInput']
    'LazyHeadlessComboboxOptions': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxOptions']
    'LazyHeadlessComboboxOption': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxOption']
    'LazyHeadlessDialog': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/dialog/dialog")['Dialog']
    'LazyHeadlessDialogOverlay': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogOverlay']
    'LazyHeadlessDialogBackdrop': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogBackdrop']
    'LazyHeadlessDialogPanel': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogPanel']
    'LazyHeadlessDialogTitle': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogTitle']
    'LazyHeadlessDialogDescription': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogDescription']
    'LazyHeadlessDisclosure': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['Disclosure']
    'LazyHeadlessDisclosureButton': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['DisclosureButton']
    'LazyHeadlessDisclosurePanel': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['DisclosurePanel']
    'LazyHeadlessFocusTrap': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/focus-trap/focus-trap")['FocusTrap']
    'LazyHeadlessListbox': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/listbox/listbox")['Listbox']
    'LazyHeadlessListboxLabel': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxLabel']
    'LazyHeadlessListboxButton': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxButton']
    'LazyHeadlessListboxOptions': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxOptions']
    'LazyHeadlessListboxOption': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxOption']
    'LazyHeadlessMenu': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/menu/menu")['Menu']
    'LazyHeadlessMenuButton': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/menu/menu")['MenuButton']
    'LazyHeadlessMenuItems': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/menu/menu")['MenuItems']
    'LazyHeadlessMenuItem': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/menu/menu")['MenuItem']
    'LazyHeadlessPopover': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/popover/popover")['Popover']
    'LazyHeadlessPopoverButton': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverButton']
    'LazyHeadlessPopoverOverlay': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverOverlay']
    'LazyHeadlessPopoverPanel': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverPanel']
    'LazyHeadlessPopoverGroup': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverGroup']
    'LazyHeadlessPortal': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/portal/portal")['Portal']
    'LazyHeadlessPortalGroup': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/portal/portal")['PortalGroup']
    'LazyHeadlessRadioGroup': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroup']
    'LazyHeadlessRadioGroupOption': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupOption']
    'LazyHeadlessRadioGroupLabel': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupLabel']
    'LazyHeadlessRadioGroupDescription': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupDescription']
    'LazyHeadlessSwitchGroup': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchGroup']
    'LazyHeadlessSwitch': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/switch/switch")['Switch']
    'LazyHeadlessSwitchLabel': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchLabel']
    'LazyHeadlessSwitchDescription': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchDescription']
    'LazyHeadlessTabGroup': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabGroup']
    'LazyHeadlessTabList': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabList']
    'LazyHeadlessTab': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/tabs/tabs")['Tab']
    'LazyHeadlessTabPanels': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabPanels']
    'LazyHeadlessTabPanel': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabPanel']
    'LazyHeadlessTransitionChild': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/transitions/transition")['TransitionChild']
    'LazyHeadlessTransitionRoot': typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/transitions/transition")['TransitionRoot']
    'LazyTresCanvas': typeof import("../node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.client.vue")['default']
    'LazyTresCanvas': IslandComponent<typeof import("../node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.server.vue")['default']>
    'LazyCarousel': typeof import("../node_modules/vue3-carousel/dist/carousel.es")['Carousel']
    'LazySlide': typeof import("../node_modules/vue3-carousel/dist/carousel.es")['Slide']
    'LazyPagination': typeof import("../node_modules/vue3-carousel/dist/carousel.es")['Pagination']
    'LazyNavigation': typeof import("../node_modules/vue3-carousel/dist/carousel.es")['Navigation']
    'LazySiteLink': typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
    'LazyRobotMeta': typeof import("../node_modules/@nuxtjs/robots/dist/runtime/nuxt/components/RobotMeta")['default']
    'LazyOgImage': typeof import("../node_modules/@nuxtjs/seo/node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImage")['default']
    'LazyOgImageScreenshot': typeof import("../node_modules/@nuxtjs/seo/node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImageScreenshot")['default']
    'LazySchemaOrgDebug': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgDebug']
    'LazySchemaOrgArticle': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgArticle']
    'LazySchemaOrgBreadcrumb': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgBreadcrumb']
    'LazySchemaOrgComment': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgComment']
    'LazySchemaOrgEvent': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgEvent']
    'LazySchemaOrgFoodEstablishment': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgFoodEstablishment']
    'LazySchemaOrgHowTo': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgHowTo']
    'LazySchemaOrgImage': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgImage']
    'LazySchemaOrgJobPosting': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgJobPosting']
    'LazySchemaOrgLocalBusiness': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgLocalBusiness']
    'LazySchemaOrgOrganization': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgOrganization']
    'LazySchemaOrgPerson': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgPerson']
    'LazySchemaOrgProduct': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgProduct']
    'LazySchemaOrgQuestion': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgQuestion']
    'LazySchemaOrgRecipe': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgRecipe']
    'LazySchemaOrgReview': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgReview']
    'LazySchemaOrgVideo': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgVideo']
    'LazySchemaOrgWebPage': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgWebPage']
    'LazySchemaOrgWebSite': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgWebSite']
    'LazySchemaOrgMovie': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgMovie']
    'LazySchemaOrgCourse': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgCourse']
    'LazySchemaOrgItemList': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgItemList']
    'LazySchemaOrgBook': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgBook']
    'LazySchemaOrgSoftwareApp': typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgSoftwareApp']
    'LazyNuxtParticles': typeof import("../node_modules/nuxt-particles/dist/runtime/components/NuxtParticles.vue")['default']
    'LazyMotion': typeof import("../node_modules/@oku-ui/motion/dist/index")['Motion']
    'LazyPresence': typeof import("../node_modules/@oku-ui/motion/dist/index")['Presence']
    'LazyPresenceGroup': typeof import("../node_modules/@oku-ui/motion/dist/index")['PresenceGroup']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const Card: typeof import("../components/content/Card.vue")['default']
export const Hero: typeof import("../components/content/Hero.vue")['default']
export const ImageContent: typeof import("../components/content/ImageContent.vue")['default']
export const ProseCode: typeof import("../components/content/ProseCode.vue")['default']
export const AppFooter: typeof import("../components/AppFooter.vue")['default']
export const AppMenu: typeof import("../components/AppMenu.vue")['default']
export const AppMenuBar: typeof import("../components/AppMenuBar.vue")['default']
export const AppMenuUpdated: typeof import("../components/AppMenuUpdated.vue")['default']
export const AppMenuV1: typeof import("../components/AppMenuV1.vue")['default']
export const AppMenuV2: typeof import("../components/AppMenuV2.vue")['default']
export const AppMenuV4: typeof import("../components/AppMenuV4.vue")['default']
export const AppMenuV5: typeof import("../components/AppMenuV5.vue")['default']
export const Auth: typeof import("../components/Auth.vue")['default']
export const ColorModeSwitch: typeof import("../components/ColorModeSwitch.vue")['default']
export const ColorModeSwitchV2: typeof import("../components/ColorModeSwitchV2.vue")['default']
export const DocumentDrivenEmpty: typeof import("../components/DocumentDrivenEmpty.vue")['default']
export const DocumentDrivenNotFound: typeof import("../components/DocumentDrivenNotFound.vue")['default']
export const EndQuizComponent: typeof import("../components/EndQuizComponent.vue")['default']
export const GeoComponent: typeof import("../components/GeoComponent.vue")['default']
export const MainQuizComponent: typeof import("../components/MainQuizComponent.vue")['default']
export const MainQuizComponentFetch: typeof import("../components/MainQuizComponentFetch.vue")['default']
export const MainQuizComponentFetchOld: typeof import("../components/MainQuizComponentFetchOld.vue")['default']
export const PrimeMegaMenu: typeof import("../components/PrimeMegaMenu.vue")['default']
export const PrimevueMenubar: typeof import("../components/PrimevueMenubar.vue")['default']
export const PrismicGallery: typeof import("../components/PrismicGallery.vue")['default']
export const ScrollToTop: typeof import("../components/ScrollToTop.vue")['default']
export const SplideGallery: typeof import("../components/SplideGallery.vue")['default']
export const StartQuizComponent: typeof import("../components/StartQuizComponent.vue")['default']
export const TableOfContents: typeof import("../components/TableOfContents.vue")['default']
export const ThemeControllerDaisy: typeof import("../components/ThemeControllerDaisy.vue")['default']
export const TopBC: typeof import("../components/TopBC.vue")['default']
export const CloudinaryGalleryComponent: typeof import("../components/cloudinaryGalleryComponent.vue")['default']
export const FlagQuizComponent: typeof import("../components/flagQuizComponent.vue")['default']
export const FlagQuizQuestions: typeof import("../components/flagQuizQuestions.vue")['default']
export const FlagQuizResults: typeof import("../components/flagQuizResults.vue")['default']
export const FlagQuizStart: typeof import("../components/flagQuizStart.vue")['default']
export const ImageGridComponent: typeof import("../components/imageGridComponent.vue")['default']
export const QuizLogic: typeof import("../components/quizLogic.vue")['default']
export const RandomCountry: typeof import("../components/randomCountry.vue")['default']
export const ContentDoc: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue")['default']
export const ContentList: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentList.vue")['default']
export const ContentNavigation: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue")['default']
export const ContentQuery: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue")['default']
export const ContentRenderer: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
export const ContentRendererMarkdown: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue")['default']
export const ContentSlot: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue")['default']
export const Markdown: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Markdown.vue")['default']
export const ProseCodeInline: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default']
export const ProsePre: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue")['default']
export const ProseA: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']
export const ProseBlockquote: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
export const ProseEm: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
export const ProseH1: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
export const ProseH2: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
export const ProseH3: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
export const ProseH4: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
export const ProseH5: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
export const ProseH6: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
export const ProseHr: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
export const ProseImg: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
export const ProseLi: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
export const ProseOl: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
export const ProseP: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
export const ProseScript: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
export const ProseStrong: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
export const ProseTable: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
export const ProseTbody: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
export const ProseTd: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
export const ProseTh: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
export const ProseThead: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
export const ProseTr: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
export const ProseUl: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
export const CookieControl: typeof import("../node_modules/@dargmuesli/nuxt-cookie-control/dist/runtime/components/CookieControl.vue")['default']
export const CookieIframe: typeof import("../node_modules/@dargmuesli/nuxt-cookie-control/dist/runtime/components/CookieIframe.vue")['default']
export const TransitionExpand: typeof import("../node_modules/@morev/vue-transitions/nuxt/vue-transitions/transition-expand.vue")['default']
export const TransitionFade: typeof import("../node_modules/@morev/vue-transitions/nuxt/vue-transitions/transition-fade.vue")['default']
export const TransitionScale: typeof import("../node_modules/@morev/vue-transitions/nuxt/vue-transitions/transition-scale.vue")['default']
export const TransitionSlide: typeof import("../node_modules/@morev/vue-transitions/nuxt/vue-transitions/transition-slide.vue")['default']
export const CldImage: typeof import("../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldImage.vue")['default']
export const CldMediaLibrary: typeof import("../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldMediaLibrary.vue")['default']
export const CldOgImage: typeof import("../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldOgImage.vue")['default']
export const CldProductGallery: typeof import("../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldProductGallery.vue")['default']
export const CldUploadButton: typeof import("../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldUploadButton.vue")['default']
export const CldUploadWidget: typeof import("../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldUploadWidget.vue")['default']
export const CldVideoPlayer: typeof import("../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldVideoPlayer.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const MDC: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
export const MDCRenderer: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
export const MDCSlot: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const Icon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const IconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const Swiper: typeof import("../node_modules/swiper/swiper-vue")['Swiper']
export const SwiperSlide: typeof import("../node_modules/swiper/swiper-vue")['SwiperSlide']
export const HeadlessCombobox: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/combobox/combobox")['Combobox']
export const HeadlessComboboxLabel: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxLabel']
export const HeadlessComboboxButton: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxButton']
export const HeadlessComboboxInput: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxInput']
export const HeadlessComboboxOptions: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxOptions']
export const HeadlessComboboxOption: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxOption']
export const HeadlessDialog: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/dialog/dialog")['Dialog']
export const HeadlessDialogOverlay: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogOverlay']
export const HeadlessDialogBackdrop: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogBackdrop']
export const HeadlessDialogPanel: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogPanel']
export const HeadlessDialogTitle: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogTitle']
export const HeadlessDialogDescription: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogDescription']
export const HeadlessDisclosure: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['Disclosure']
export const HeadlessDisclosureButton: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['DisclosureButton']
export const HeadlessDisclosurePanel: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['DisclosurePanel']
export const HeadlessFocusTrap: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/focus-trap/focus-trap")['FocusTrap']
export const HeadlessListbox: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/listbox/listbox")['Listbox']
export const HeadlessListboxLabel: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxLabel']
export const HeadlessListboxButton: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxButton']
export const HeadlessListboxOptions: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxOptions']
export const HeadlessListboxOption: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxOption']
export const HeadlessMenu: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/menu/menu")['Menu']
export const HeadlessMenuButton: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/menu/menu")['MenuButton']
export const HeadlessMenuItems: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/menu/menu")['MenuItems']
export const HeadlessMenuItem: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/menu/menu")['MenuItem']
export const HeadlessPopover: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/popover/popover")['Popover']
export const HeadlessPopoverButton: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverButton']
export const HeadlessPopoverOverlay: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverOverlay']
export const HeadlessPopoverPanel: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverPanel']
export const HeadlessPopoverGroup: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverGroup']
export const HeadlessPortal: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/portal/portal")['Portal']
export const HeadlessPortalGroup: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/portal/portal")['PortalGroup']
export const HeadlessRadioGroup: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroup']
export const HeadlessRadioGroupOption: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupOption']
export const HeadlessRadioGroupLabel: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupLabel']
export const HeadlessRadioGroupDescription: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupDescription']
export const HeadlessSwitchGroup: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchGroup']
export const HeadlessSwitch: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/switch/switch")['Switch']
export const HeadlessSwitchLabel: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchLabel']
export const HeadlessSwitchDescription: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchDescription']
export const HeadlessTabGroup: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabGroup']
export const HeadlessTabList: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabList']
export const HeadlessTab: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/tabs/tabs")['Tab']
export const HeadlessTabPanels: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabPanels']
export const HeadlessTabPanel: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabPanel']
export const HeadlessTransitionChild: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/transitions/transition")['TransitionChild']
export const HeadlessTransitionRoot: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/transitions/transition")['TransitionRoot']
export const TresCanvas: typeof import("../node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.client.vue")['default']
export const TresCanvas: IslandComponent<typeof import("../node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.server.vue")['default']>
export const Carousel: typeof import("../node_modules/vue3-carousel/dist/carousel.es")['Carousel']
export const Slide: typeof import("../node_modules/vue3-carousel/dist/carousel.es")['Slide']
export const Pagination: typeof import("../node_modules/vue3-carousel/dist/carousel.es")['Pagination']
export const Navigation: typeof import("../node_modules/vue3-carousel/dist/carousel.es")['Navigation']
export const SiteLink: typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
export const RobotMeta: typeof import("../node_modules/@nuxtjs/robots/dist/runtime/nuxt/components/RobotMeta")['default']
export const OgImage: typeof import("../node_modules/@nuxtjs/seo/node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImage")['default']
export const OgImageScreenshot: typeof import("../node_modules/@nuxtjs/seo/node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImageScreenshot")['default']
export const SchemaOrgDebug: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgDebug']
export const SchemaOrgArticle: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgArticle']
export const SchemaOrgBreadcrumb: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgBreadcrumb']
export const SchemaOrgComment: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgComment']
export const SchemaOrgEvent: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgEvent']
export const SchemaOrgFoodEstablishment: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgFoodEstablishment']
export const SchemaOrgHowTo: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgHowTo']
export const SchemaOrgImage: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgImage']
export const SchemaOrgJobPosting: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgJobPosting']
export const SchemaOrgLocalBusiness: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgLocalBusiness']
export const SchemaOrgOrganization: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgOrganization']
export const SchemaOrgPerson: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgPerson']
export const SchemaOrgProduct: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgProduct']
export const SchemaOrgQuestion: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgQuestion']
export const SchemaOrgRecipe: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgRecipe']
export const SchemaOrgReview: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgReview']
export const SchemaOrgVideo: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgVideo']
export const SchemaOrgWebPage: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgWebPage']
export const SchemaOrgWebSite: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgWebSite']
export const SchemaOrgMovie: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgMovie']
export const SchemaOrgCourse: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgCourse']
export const SchemaOrgItemList: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgItemList']
export const SchemaOrgBook: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgBook']
export const SchemaOrgSoftwareApp: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgSoftwareApp']
export const NuxtParticles: typeof import("../node_modules/nuxt-particles/dist/runtime/components/NuxtParticles.vue")['default']
export const Motion: typeof import("../node_modules/@oku-ui/motion/dist/index")['Motion']
export const Presence: typeof import("../node_modules/@oku-ui/motion/dist/index")['Presence']
export const PresenceGroup: typeof import("../node_modules/@oku-ui/motion/dist/index")['PresenceGroup']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyCard: typeof import("../components/content/Card.vue")['default']
export const LazyHero: typeof import("../components/content/Hero.vue")['default']
export const LazyImageContent: typeof import("../components/content/ImageContent.vue")['default']
export const LazyProseCode: typeof import("../components/content/ProseCode.vue")['default']
export const LazyAppFooter: typeof import("../components/AppFooter.vue")['default']
export const LazyAppMenu: typeof import("../components/AppMenu.vue")['default']
export const LazyAppMenuBar: typeof import("../components/AppMenuBar.vue")['default']
export const LazyAppMenuUpdated: typeof import("../components/AppMenuUpdated.vue")['default']
export const LazyAppMenuV1: typeof import("../components/AppMenuV1.vue")['default']
export const LazyAppMenuV2: typeof import("../components/AppMenuV2.vue")['default']
export const LazyAppMenuV4: typeof import("../components/AppMenuV4.vue")['default']
export const LazyAppMenuV5: typeof import("../components/AppMenuV5.vue")['default']
export const LazyAuth: typeof import("../components/Auth.vue")['default']
export const LazyColorModeSwitch: typeof import("../components/ColorModeSwitch.vue")['default']
export const LazyColorModeSwitchV2: typeof import("../components/ColorModeSwitchV2.vue")['default']
export const LazyDocumentDrivenEmpty: typeof import("../components/DocumentDrivenEmpty.vue")['default']
export const LazyDocumentDrivenNotFound: typeof import("../components/DocumentDrivenNotFound.vue")['default']
export const LazyEndQuizComponent: typeof import("../components/EndQuizComponent.vue")['default']
export const LazyGeoComponent: typeof import("../components/GeoComponent.vue")['default']
export const LazyMainQuizComponent: typeof import("../components/MainQuizComponent.vue")['default']
export const LazyMainQuizComponentFetch: typeof import("../components/MainQuizComponentFetch.vue")['default']
export const LazyMainQuizComponentFetchOld: typeof import("../components/MainQuizComponentFetchOld.vue")['default']
export const LazyPrimeMegaMenu: typeof import("../components/PrimeMegaMenu.vue")['default']
export const LazyPrimevueMenubar: typeof import("../components/PrimevueMenubar.vue")['default']
export const LazyPrismicGallery: typeof import("../components/PrismicGallery.vue")['default']
export const LazyScrollToTop: typeof import("../components/ScrollToTop.vue")['default']
export const LazySplideGallery: typeof import("../components/SplideGallery.vue")['default']
export const LazyStartQuizComponent: typeof import("../components/StartQuizComponent.vue")['default']
export const LazyTableOfContents: typeof import("../components/TableOfContents.vue")['default']
export const LazyThemeControllerDaisy: typeof import("../components/ThemeControllerDaisy.vue")['default']
export const LazyTopBC: typeof import("../components/TopBC.vue")['default']
export const LazyCloudinaryGalleryComponent: typeof import("../components/cloudinaryGalleryComponent.vue")['default']
export const LazyFlagQuizComponent: typeof import("../components/flagQuizComponent.vue")['default']
export const LazyFlagQuizQuestions: typeof import("../components/flagQuizQuestions.vue")['default']
export const LazyFlagQuizResults: typeof import("../components/flagQuizResults.vue")['default']
export const LazyFlagQuizStart: typeof import("../components/flagQuizStart.vue")['default']
export const LazyImageGridComponent: typeof import("../components/imageGridComponent.vue")['default']
export const LazyQuizLogic: typeof import("../components/quizLogic.vue")['default']
export const LazyRandomCountry: typeof import("../components/randomCountry.vue")['default']
export const LazyContentDoc: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue")['default']
export const LazyContentList: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentList.vue")['default']
export const LazyContentNavigation: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue")['default']
export const LazyContentQuery: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue")['default']
export const LazyContentRenderer: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
export const LazyContentRendererMarkdown: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue")['default']
export const LazyContentSlot: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue")['default']
export const LazyMarkdown: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Markdown.vue")['default']
export const LazyProseCodeInline: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default']
export const LazyProsePre: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue")['default']
export const LazyProseA: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']
export const LazyProseBlockquote: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
export const LazyProseEm: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
export const LazyProseH1: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
export const LazyProseH2: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
export const LazyProseH3: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
export const LazyProseH4: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
export const LazyProseH5: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
export const LazyProseH6: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
export const LazyProseHr: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
export const LazyProseImg: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
export const LazyProseLi: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
export const LazyProseOl: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
export const LazyProseP: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
export const LazyProseScript: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
export const LazyProseStrong: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
export const LazyProseTable: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
export const LazyProseTbody: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
export const LazyProseTd: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
export const LazyProseTh: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
export const LazyProseThead: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
export const LazyProseTr: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
export const LazyProseUl: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
export const LazyCookieControl: typeof import("../node_modules/@dargmuesli/nuxt-cookie-control/dist/runtime/components/CookieControl.vue")['default']
export const LazyCookieIframe: typeof import("../node_modules/@dargmuesli/nuxt-cookie-control/dist/runtime/components/CookieIframe.vue")['default']
export const LazyTransitionExpand: typeof import("../node_modules/@morev/vue-transitions/nuxt/vue-transitions/transition-expand.vue")['default']
export const LazyTransitionFade: typeof import("../node_modules/@morev/vue-transitions/nuxt/vue-transitions/transition-fade.vue")['default']
export const LazyTransitionScale: typeof import("../node_modules/@morev/vue-transitions/nuxt/vue-transitions/transition-scale.vue")['default']
export const LazyTransitionSlide: typeof import("../node_modules/@morev/vue-transitions/nuxt/vue-transitions/transition-slide.vue")['default']
export const LazyCldImage: typeof import("../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldImage.vue")['default']
export const LazyCldMediaLibrary: typeof import("../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldMediaLibrary.vue")['default']
export const LazyCldOgImage: typeof import("../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldOgImage.vue")['default']
export const LazyCldProductGallery: typeof import("../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldProductGallery.vue")['default']
export const LazyCldUploadButton: typeof import("../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldUploadButton.vue")['default']
export const LazyCldUploadWidget: typeof import("../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldUploadWidget.vue")['default']
export const LazyCldVideoPlayer: typeof import("../node_modules/@nuxtjs/cloudinary/dist/runtime/components/CldVideoPlayer.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const LazyMDC: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
export const LazyMDCRenderer: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
export const LazyMDCSlot: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
export const LazyColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const LazyIcon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const LazyIconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const LazySwiper: typeof import("../node_modules/swiper/swiper-vue")['Swiper']
export const LazySwiperSlide: typeof import("../node_modules/swiper/swiper-vue")['SwiperSlide']
export const LazyHeadlessCombobox: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/combobox/combobox")['Combobox']
export const LazyHeadlessComboboxLabel: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxLabel']
export const LazyHeadlessComboboxButton: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxButton']
export const LazyHeadlessComboboxInput: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxInput']
export const LazyHeadlessComboboxOptions: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxOptions']
export const LazyHeadlessComboboxOption: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxOption']
export const LazyHeadlessDialog: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/dialog/dialog")['Dialog']
export const LazyHeadlessDialogOverlay: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogOverlay']
export const LazyHeadlessDialogBackdrop: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogBackdrop']
export const LazyHeadlessDialogPanel: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogPanel']
export const LazyHeadlessDialogTitle: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogTitle']
export const LazyHeadlessDialogDescription: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogDescription']
export const LazyHeadlessDisclosure: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['Disclosure']
export const LazyHeadlessDisclosureButton: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['DisclosureButton']
export const LazyHeadlessDisclosurePanel: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['DisclosurePanel']
export const LazyHeadlessFocusTrap: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/focus-trap/focus-trap")['FocusTrap']
export const LazyHeadlessListbox: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/listbox/listbox")['Listbox']
export const LazyHeadlessListboxLabel: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxLabel']
export const LazyHeadlessListboxButton: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxButton']
export const LazyHeadlessListboxOptions: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxOptions']
export const LazyHeadlessListboxOption: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxOption']
export const LazyHeadlessMenu: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/menu/menu")['Menu']
export const LazyHeadlessMenuButton: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/menu/menu")['MenuButton']
export const LazyHeadlessMenuItems: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/menu/menu")['MenuItems']
export const LazyHeadlessMenuItem: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/menu/menu")['MenuItem']
export const LazyHeadlessPopover: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/popover/popover")['Popover']
export const LazyHeadlessPopoverButton: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverButton']
export const LazyHeadlessPopoverOverlay: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverOverlay']
export const LazyHeadlessPopoverPanel: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverPanel']
export const LazyHeadlessPopoverGroup: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverGroup']
export const LazyHeadlessPortal: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/portal/portal")['Portal']
export const LazyHeadlessPortalGroup: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/portal/portal")['PortalGroup']
export const LazyHeadlessRadioGroup: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroup']
export const LazyHeadlessRadioGroupOption: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupOption']
export const LazyHeadlessRadioGroupLabel: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupLabel']
export const LazyHeadlessRadioGroupDescription: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupDescription']
export const LazyHeadlessSwitchGroup: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchGroup']
export const LazyHeadlessSwitch: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/switch/switch")['Switch']
export const LazyHeadlessSwitchLabel: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchLabel']
export const LazyHeadlessSwitchDescription: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchDescription']
export const LazyHeadlessTabGroup: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabGroup']
export const LazyHeadlessTabList: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabList']
export const LazyHeadlessTab: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/tabs/tabs")['Tab']
export const LazyHeadlessTabPanels: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabPanels']
export const LazyHeadlessTabPanel: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabPanel']
export const LazyHeadlessTransitionChild: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/transitions/transition")['TransitionChild']
export const LazyHeadlessTransitionRoot: typeof import("../node_modules/nuxt-headlessui/node_modules/@headlessui/vue/dist/components/transitions/transition")['TransitionRoot']
export const LazyTresCanvas: typeof import("../node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.client.vue")['default']
export const LazyTresCanvas: IslandComponent<typeof import("../node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.server.vue")['default']>
export const LazyCarousel: typeof import("../node_modules/vue3-carousel/dist/carousel.es")['Carousel']
export const LazySlide: typeof import("../node_modules/vue3-carousel/dist/carousel.es")['Slide']
export const LazyPagination: typeof import("../node_modules/vue3-carousel/dist/carousel.es")['Pagination']
export const LazyNavigation: typeof import("../node_modules/vue3-carousel/dist/carousel.es")['Navigation']
export const LazySiteLink: typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
export const LazyRobotMeta: typeof import("../node_modules/@nuxtjs/robots/dist/runtime/nuxt/components/RobotMeta")['default']
export const LazyOgImage: typeof import("../node_modules/@nuxtjs/seo/node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImage")['default']
export const LazyOgImageScreenshot: typeof import("../node_modules/@nuxtjs/seo/node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImageScreenshot")['default']
export const LazySchemaOrgDebug: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgDebug']
export const LazySchemaOrgArticle: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgArticle']
export const LazySchemaOrgBreadcrumb: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgBreadcrumb']
export const LazySchemaOrgComment: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgComment']
export const LazySchemaOrgEvent: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgEvent']
export const LazySchemaOrgFoodEstablishment: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgFoodEstablishment']
export const LazySchemaOrgHowTo: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgHowTo']
export const LazySchemaOrgImage: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgImage']
export const LazySchemaOrgJobPosting: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgJobPosting']
export const LazySchemaOrgLocalBusiness: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgLocalBusiness']
export const LazySchemaOrgOrganization: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgOrganization']
export const LazySchemaOrgPerson: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgPerson']
export const LazySchemaOrgProduct: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgProduct']
export const LazySchemaOrgQuestion: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgQuestion']
export const LazySchemaOrgRecipe: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgRecipe']
export const LazySchemaOrgReview: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgReview']
export const LazySchemaOrgVideo: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgVideo']
export const LazySchemaOrgWebPage: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgWebPage']
export const LazySchemaOrgWebSite: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgWebSite']
export const LazySchemaOrgMovie: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgMovie']
export const LazySchemaOrgCourse: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgCourse']
export const LazySchemaOrgItemList: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgItemList']
export const LazySchemaOrgBook: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgBook']
export const LazySchemaOrgSoftwareApp: typeof import("../node_modules/@unhead/schema-org/dist/vue")['SchemaOrgSoftwareApp']
export const LazyNuxtParticles: typeof import("../node_modules/nuxt-particles/dist/runtime/components/NuxtParticles.vue")['default']
export const LazyMotion: typeof import("../node_modules/@oku-ui/motion/dist/index")['Motion']
export const LazyPresence: typeof import("../node_modules/@oku-ui/motion/dist/index")['Presence']
export const LazyPresenceGroup: typeof import("../node_modules/@oku-ui/motion/dist/index")['PresenceGroup']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
